### ISSUE TITLE
Not all copper is meltable in a crucible

### ISSUE THREAD

**Issue by ZeekDaGeek** [Flaxbeard/Flaxbeards-Steam-Power#158]
Forge version: 10.13.2.1236
Mod version: 0.27.1
Other mods: http://tinyurl.com/wwpack

Not all copper seems to be meltable in a crucible. Specifically when attempting to melt Tinkers' Construct Copper I was not able to get it to go into either crucible.

**Comment by BoredomKils** [comment]
Yep, got the issue with Mekanism too.  The workaround is nice, but a proper fix would be really cool.

**Comment by xbony2** [comment]
@ZeekDaGeek can you reconfirm this bug?

**Comment by ZeekDaGeek** [comment]
This bug seems to be fixed in the newest versions.
