### ISSUE TITLE
Can't cast village server crash

### ISSUE THREAD

**Issue by PsionicArchon** [Flaxbeard/Flaxbeards-Steam-Power#165]
I thought this one got nipped several versions ago.

Crash log: http://pastebin.com/3HPvhtBA

It happens when a player generates a village that spawns with a steam boiler in it.

I am using a standard forge server with the latest version of flaxbeard's.

**Comment by Gholuk** [comment]
True. TileEntitySteamPipe is not used. But pipes are placed and they go along with TESteamPipe of cause. Maybe this issue occurs if a village is generated twice in the same position and/or the TESteamPipe of a previous placed pipe is not removed correctly. Anyway. Check my pull request, it should fix this issue.
