### ISSUE TITLE
Server Crash when shift-clicking Esteem Innovation on an object from FSP

### ISSUE THREAD

**Issue by darkreaper44** [Flaxbeard/Flaxbeards-Steam-Power#168]
When shift clicking an object from flax with the book "Esteemed Innovation" it will crash the server.

Nope a major big deal but thought i would let you know, 

Cheers

**Comment by BoredomKils** [comment]
I've got this issue as well.  The log, if it helps: http://pastebin.com/gS3NDTsC

**Comment by InsaneJ** [comment]
Same here. Dedicated server crashes when you shift-click with the Esteemed Innovations book. Crash report: http://paste2.org/_L5mkfWPW

**Comment by elifoster** [comment]
Unfortunately, since this is a strictly-server-side issue, I won't be able to test/fix it. @xbony2 is your computer powerful enough to run server and client at the same time?

**Comment by xbony2** [comment]
I can run multiple clients/LAN fine, but making a server is problematic because my IP address is never the IP :P but it does crash in LAN, last time I tested.

**Comment by elifoster** [comment]
Okay, so I am assigning you this issue.
