### ISSUE TITLE
Crash when inserting/extracting Steam (non-IC2) into Pressure Converter

### ISSUE THREAD

**Issue by mallrat208** [Flaxbeard/Flaxbeards-Steam-Power#172]
The full crash log is at: 
https://gist.github.com/mallrat208/5a3a545473a8e1269a50

I was able to successfully extract steam from the converter using a liquid transfer node without any issue. Insertion using the transfer node however resulted in the above crash.

I'm using the newest release of both FSP and ExU as well as Forge 1227

**Comment by elifoster** [comment]
This was actually fixed in #188.
