### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Xee1** [Flaxbeard/Flaxbeards-Steam-Power#174]
http://pastebin.com/PCMLWc6P
I think is ValvePipe

**Comment by master801** [comment]
I'm going to assume that the direction it gets (which is zero in the list), is null. Thus causing this error.

https://github.com/Flaxbeard/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/tile/TileEntityValvePipe.java#L141

**Comment by elifoster** [comment]
This was fixed in @7301a4d

**Comment by Xee1** [comment]
Thanks!
