### ISSUE TITLE
AOBD Support

### ISSUE THREAD

**Issue by AegisLesha** [Flaxbeard/Flaxbeards-Steam-Power#176]
Not really a new request, as I already asked @satanicsanta and @ganymedes01 about it (https://twitter.com/ModdingAegisSrx/status/539452989187317760), but it's just to make an "official" request here and more or less shout to people interested in AOBD that support may come

Because it's basically changing the API so mods like AOBD can add ores to FSP's ore processing

**Comment by xbony2** [comment]
*Cough* #120

**Comment by AegisLesha** [comment]
Oh....Oh ok! Fine then, I close ^^
