### ISSUE TITLE
Baubles API Dependency bug

### ISSUE THREAD

**Issue by master801** [Flaxbeard/Flaxbeards-Steam-Power#177]
Since this is an api, you should NOT be depending on the main mod's classes without some kind of form to get the version it's at. (Hint, Java Reflection)

https://github.com/Flaxbeard/Flaxbeards-Steam-Power/blob/master/src/api/java/baubles/api/package-info.java#L1

**Comment by xbony2** [comment]
See: https://github.com/Azanor/Baubles/issues/80

So I don't think reflection is really necessary. Going to update it with Bauble's latest API.

**Comment by xbony2** [comment]
Might be worth looking into updating other mod's APIs, on a related note.
