### ISSUE TITLE
FSP Pressure Converter Crash w/ EIO Fluid Conduit

### ISSUE THREAD

**Issue by Nentify** [Flaxbeard/Flaxbeards-Steam-Power#178]
https://github.com/Tekkify/Tekkify/issues/7
https://github.com/CrazyPants/EnderIO/issues/1590

**Comment by satanicsanta** [comment]
Known issue and not an EIO related one either #172

**Comment by satanicsanta** [comment]
Also @xbony2 crash bugs are always prio:high :P
