### ISSUE TITLE
Wrong material for Engineering Table(?)

### ISSUE THREAD

**Issue by Adaptivity** [Flaxbeard/Flaxbeards-Steam-Power#181]
https://github.com/Flaxbeard/Flaxbeards-Steam-Power/blob/52fc2206a7fac01c2509648c14be4038ac219be9/src/main/java/flaxbeard/steamcraft/block/BlockEngineeringTable.java#L22
It's made from cobblestone but it's wood? And requires axe to break it.

**Comment by xbony2** [comment]
I blame Santa. Or maybe Flaxbeard decided the Engineering Table would be made of wood, but decided to change it to stone, and forgot to change the material.

**Comment by satanicsanta** [comment]
I take no responsibility.

**Comment by xbony2** [comment]
Then it's Flaxbeard's fault! :P btw, should we change it to material.iron instead of material.rock? I think rock makes more sense, but I dunno.

**Comment by Adaptivity** [comment]
I think it should stay material.rock. It definitely makes more sense.

**Comment by satanicsanta** [comment]
Keep it at rock
