### ISSUE TITLE
Balancing or config options? (speed/steam)

### ISSUE THREAD

**Issue by CurePindal** [Flaxbeard/Flaxbeards-Steam-Power#184]
Hello! We are fiddling with this fantastic mod for a few weeks now. We really like the rather low-tech/Steampunk approach over most other hightech mods.

Many players mentioned that we could need some balancing. For one the Exo suits run-speed is really too fast and the overall steam consumption of the suit is way too low. (especially when using the jetpacks) Most of our players never upgrade the basic steam tank in the suit, because the steam supply is usually enough.

Can you please either adjust the values or add config options to adjust them? 
Thanks for considering.

EDIT BY SANTA:
* [x] Exosuit run-speed configuration
* [x] Exosuit steam consumption rate configuration
* [x] Steam tool steam consumption rate configuration
* [x] Jetpack steam consumption
* [x] Thruster consumption
* [x] Jump boost consumption
* [x] Steam Hammer consumption
* [x] Tank size configuration
* [x] Power Fist consumption rate configuration
* [x] Fan consumption
* [x] Archimedes Screw consumption
* [x] Steam Heater consumption
* [x] Vacuum consumption

**Comment by xbony2** [comment]
I'll look into adding config options :)

**Comment by CurePindal** [comment]
Many thanks!

**Comment by Ghoughpteighbteau** [comment]
I've noticed this in my personal playthrough as well, some of these numbers seem wrong

Drills and saws are a bit slow given how fantastically cool they are, and the suit's endless supply of steam basically gives me an unending jetpack. Higher Consumption is likely the best answer here.

**Comment by CurePindal** [comment]
You know that you have to speed up the drill and saw, right? Because at max speed they are incredibly fast. And from my experience the tools feel just right balanced in regards of speed, steam-usage and how long they last.
