### ISSUE TITLE
Vacuum fails to stop sucking clientside only when it runs out of steam

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [Flaxbeard/Flaxbeards-Steam-Power#189]
This is definitely part of the bug reported in #186 and might be a part of the problem in #187

To reproduce, feed a vacuum steam behind a valve, cut off valve, vacuum goes forever and will not stop until broken.

Interesting side note: If you actively release the steam vent side, it will sometimes stop! I don't fully understand the steam network yet. 

strangeness: 
This keeps going forever on the client side, but the server sees it as stopped. Hitting it with a wrench doesn't seem to help
![Goes forever](http://i.imgur.com/Rns7IcL.png)
opening the valve for the pipe sometimes does stop the vacuum, but sometimes you gotta hit it with a wrench to get it to stop
![This sometimes stops it](http://i.imgur.com/dNeJf4k.png)
server side behavior seems correct, vacuum resumes on steam normally.
![Resumes on more steam](http://i.imgur.com/moxaDT4.png)

**Comment by Ghoughpteighbteau** [comment]
I don't fully 100% understand the steam network, and I don't think i'm going to be able to fix this easily...

Do you mind if I try a rewrite of the vacuum logic and see where that gets me?

**Comment by xbony2** [comment]
With the amount of issues with the vacuum, a rewrite is probably a good idea :octocat:

**Comment by Gholuk** [comment]
"Someone" reported this before ( see Issue  #52 ), but then I did not understand the code as I do now and I can tell you now: It will run endless, as the "active" variable is never set to "false" at any time (unless you reload the chunk). Wether you want to rewrite the vacuum or not, I posted a possible solution.

**Comment by Ghoughpteighbteau** [comment]
@Gholuk it did shutdown occasionally in my testing. 

[This is the line that was causing the vacuum to stop spinning client side](https://github.com/Flaxbeard/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/tile/TileEntityVacuum.java#L274)

This actually makes a bit of sense seeing as the server is the one that manages the steam network, as far as I understand. It would be the one to report on the vacuum stopping.

**Comment by Gholuk** [comment]
Yes, I know, but this variable is only updated here:
https://github.com/Flaxbeard/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/tile/TileEntityVacuum.java#L264
And "getDescriptionPaket" is not called often. I see it during chunk loading / initialization only. Even an "onNeighborChange" does not call it. If you want to shut down this machine, you need to check and update the variable somewhere else.
