### ISSUE TITLE
Crash on Rock Smasher activation 0.27.4

### ISSUE THREAD

**Issue by buymytoasters** [Flaxbeard/Flaxbeards-Steam-Power#200]
Just installed 0.27.4, created a new creative world, and tried placing a few ores in a rock smasher setup.  The following crash happened each time with various ores.

Sample: http://pastebin.com/HqaRzU6f

**Comment by xbony2** [comment]
You've failed us @ganymedes01 :P

**Comment by ganymedes01** [comment]
whoopsies XD
Let me see what I did wrong...

**Comment by ganymedes01** [comment]
forgotten null check...
