### ISSUE TITLE
0.27.3 Valve Pipe status wrong on reload?

### ISSUE THREAD

**Issue by CurePindal** [Flaxbeard/Flaxbeards-Steam-Power#202]
Hello!

Ive noticed that my closed Valve pipe always acts as if its open when I load my singleplayer world. 
But it was closed when saved and the model also still shows the closed status. Steam is flowing, tough.
Turning the valve open and then closing it again solves the issue.

**Comment by Ghoughpteighbteau** [comment]
arg. I've tried to catch this bug, but I can't seem to reproduce it... Is it consistently happening?

**Comment by CurePindal** [comment]
Yes. Every time I reload my singleplayer world my only valve pipe behaves wrong. (its closed but lets flow steam to the attached thumper).

**Comment by Gholuk** [comment]
Why don't you install 0.27.4? I fixed it already and the fix is included in 0.27.4...

**Comment by CurePindal** [comment]
First, .27.4 was pretty much released on the same day Ive started my new world, so a bit close to notice the release.
Then, theres a critical bug with thumpers and ores reported in .27.4. Makes it and unplayable release. However I will build from source in a few mins.

**Comment by satanicsanta** [comment]
Yeah, I tried to build 0.27.5 with the critical crash bug fixed, but for some reason ForgeGradle was being a poop, and I've been very busy.
