### ISSUE TITLE
game crashes when you crush lapis or redstone ores

### ISSUE THREAD

**Issue by shivachirr** [Flaxbeard/Flaxbeards-Steam-Power#204]
i just know the moment i add lapis restone ores the game crashes i also think emerlas and diamond casue it not fully sure

**Comment by Gholuk** [comment]
See Issue #200 and Issue #203 
Fix for the problem is already implemented and a new build with the rock smasher working again should be available soon.

**Comment by shivachirr** [comment]
ok good to know

**Comment by satanicsanta** [comment]
Duplicate of #200.
