### ISSUE TITLE
Steam Hammers have a huge FPS hit

### ISSUE THREAD

**Issue by Gunre** [Flaxbeard/Flaxbeards-Steam-Power#206]
After setting up my first steam setup on my server I noticed my FPS plummet.  After trial and error removing blocks, I discovered it was the steam hammer that was causing it.  It was the difference between 180+ FPS without a steam hammer placed, and 20-40 FPS with one placed.  
This was on the latest version of the Resonant Rise 3 modpack, 'mainline' install, which has the current release of the mod (1.7.10-0.27.4)

**Comment by CurePindal** [comment]
Can confirm a strange FPS drop from the hammer with the current source code. (from 145fps down to ~105)
