### ISSUE TITLE
Exosuit vs Bibliocraft Armor stand issues

### ISSUE THREAD

**Issue by CurePindal** [Flaxbeard/Flaxbeards-Steam-Power#208]
2 issues Ive noticed when using the armor stands from Bibliocraft:

1. Exo suit armor plates arent rendered when you place the suit on an armor stand.

2. Exo suit features like step assist arent removed when you remove the exosuit by shift-clicking the armor stand. The feature stays with you until you relog or reload the game.

Not sure if this issues come from Steam Power or Bibliocraft.

**Comment by satanicsanta** [comment]
Both of these are known issues.
