### ISSUE TITLE
Game crash from rock smasher

### ISSUE THREAD

**Issue by kremlar** [Flaxbeard/Flaxbeards-Steam-Power#209]
Using the rock smasher in block breaking mode causes the game to immediately crash in version 27.4. Reloading the world file gives a nice repeating block breaking sound until you destroy the rock smashers. Blocks break properly using 27.3 on the same world file.

Full crash report and screenshot below.

http://pastebin.com/80tDU46K
http://imgur.com/cMgZA42

**Comment by satanicsanta** [comment]
Issue is fixed in next build. #200
