### ISSUE TITLE
Flaxbeard rocket launcher doesn't obey mobGriefing gamerule - 0.27.5

### ISSUE THREAD

**Issue by keenerb** [Flaxbeard/Flaxbeards-Steam-Power#211]
It appears the rocket launcher will destroy blocks regardless of whether explosions are enabled or not?

**Comment by xbony2** [comment]
Is this the same with TNT?

**Comment by keenerb** [comment]
Actually, yes.  Maybe mobGriefing doesn't cover explosions.

Is there an option to disable rocket launcher block damage?  If not, can it be added?

**Comment by xbony2** [comment]
That kinda turns this bug report into a feature request :P

**Comment by keenerb** [comment]
A bit, yes.  Just a bit.

**Comment by xbony2** [comment]
Makes to easier to do though, IMO, since figuring out the game rules and stuff is something I don't know about.

**Comment by satanicsanta** [comment]
Yes. Screw gamerules :D

**Comment by xbony2** [comment]
Commit 677 fixed this. Annoying that it wasn't auto-closed.

**Comment by satanicsanta** [comment]
@xbony2 You said "Fixes #221" rather than "Fixes #211".

**Comment by xbony2** [comment]
dang it
