### ISSUE TITLE
Crash when using crusher with dirt or sand

### ISSUE THREAD

**Issue by LarryTee** [Flaxbeard/Flaxbeards-Steam-Power#213]
When using crusher with Dirt or sand will crash server

**Comment by elifoster** [comment]
@LarryTee Please provide more information. This is not enough to diagnose a bug.

**Comment by xbony2** [comment]
Dat avatar though.

**Comment by elifoster** [comment]
I just checked, and this does not actually happen. Closing.

**Comment by elifoster** [comment]
Although you did help me find a different bug, fixed in @d0cc83b.
