### ISSUE TITLE
Generating ores in other mod's dimension

### ISSUE THREAD

**Issue by zuoanqh** [Flaxbeard/Flaxbeards-Steam-Power#214]
Hi.

zinc and copper from this mod is not generating in other mod's dimensions. This cause real trouble to me because I can't regen the overworld just for this mod and erase everything i built. and If I decide to live in, say twilight forest, I will not be able to mine the ores I need there.

**Comment by elifoster** [comment]
Yeah, a config for more dimensions would be pretty neat-o. In the meantime, you should be able to get the ores from the nether.

**Comment by elifoster** [comment]
By the way, as of right now, it will only generate in stone. This can be quite limiting for very custom dimensions. I'm not sure how else to do it right now. Perhaps we should just generate it below a certain level in these custom dims? @xbony2 ?

**Comment by xbony2** [comment]
We could probably add some mod support to the dimensions that need it. The only thing I can think of is Twilight Forest and Galacticraft.

**Comment by elifoster** [comment]
Eh. I dunno. I think it would be much safer to just do it below Y=70 or something for dimensions defined in the config.
