### ISSUE TITLE
Overworld copper genaration

### ISSUE THREAD

**Issue by jem991** [Flaxbeard/Flaxbeards-Steam-Power#218]
I'm use cofh ore generation. close the steampower copper config but genaration the steampower copper overworl I'm use last version

**Comment by xbony2** [comment]
Uh, the config for generating copper ore is off, but it's generating anyway?

**Comment by jem991** [comment]
yes exactly.

**Comment by xbony2** [comment]
Is Tin in the same state, or is it ok?

**Comment by jem991** [comment]
Tin is ok only copper

**Comment by xbony2** [comment]
Right >.>

**Comment by xbony2** [comment]
I'm almost certain you've made some sort of mistake. From looking at the code, there's no way this could happen, unless another mod breaks it somehow.

**Comment by xbony2** [comment]
Make sure the config file is not somehow corrupted- it might be worth deleting it and making a new one.

**Comment by elifoster** [comment]
I'm not almost certain. I am certain. There's literally no way that code could fail in a way that is not user error.
