### ISSUE TITLE
Archimedes Screw not working

### ISSUE THREAD

**Issue by ionlyneedthisforbugs** [Flaxbeard/Flaxbeards-Steam-Power#225]
So I set up my boiler and stuff like I normally do (flash boiler) and got my setup in my house, my archimedes screw was alright for about 10 minutes then it stopped working? I looked in my boiler, it still had 35 coal in it. But the screw wouldn't work? I got it working again by using buckets of water but I need it automated, i'm still quite new to this mod, help?

**Comment by elifoster** [comment]
It probably just ran out of steam.

**Comment by Zenith-One** [comment]
Could you provide a screenshot? It's possibly a positioning issue.

**Comment by viperfang1** [comment]
I'm having this issue as well.  [See screenshots](https://imgur.com/a/2xUMn).
Version Info: 1.7.10-0.28.3

**Comment by Zenith-One** [comment]
If I recall correctly, boilers only output steam from the top

**Comment by elifoster** [comment]
User error. The screw needs steam piped into it.

**Comment by viperfang1** [comment]
I was not aware that was necessary.  Thanks for the info!

**Comment by elifoster** [comment]
Be sure to check the official wiki (on the FTB CurseGamepedia site)
