### ISSUE TITLE
Crash related to #224 fix - NumberFormatException

### ISSUE THREAD

**Issue by kylemcqueen75** [Flaxbeard/Flaxbeards-Steam-Power#230]
http://pastebin.com/z8h2LsiF

Loading a new world single player, creative. Might be related to issue #224

**Comment by Sunconure11** [comment]
I'm having the same issue in my server.

**Comment by InFerNos1** [comment]
Same issue here, using Flaxbeard'sSteamPower-1.7.10-0.28.3.jar
http://pastebin.com/FVDbQHVW

**Comment by kylemcqueen75** [comment]
Yep, its related to the fix for #224 
I Imagine a fix will be close behind.

**Comment by InFerNos1** [comment]
Yeah, I downgraded to 0.28.2 to stop the world from crashing in the overworld, I just won't leave dim0 until this whole thing it fixed. I've been having issues with an invisible nether, which I found was caused by #224.
http://www.minecraftforum.net/forums/support/modded-client-support/2375987-resolved-invisible-nether-and-end-after-a-few is where I asked for help. I'm glad I found the cause, it's been bugging me for days.

**Comment by kylemcqueen75** [comment]
I use http://www.curse.com/mc-mods/minecraft/224867-flaxbeards-steam-power/2227730
Haven't had any issues with that version yet :P

**Comment by Monstrel** [comment]
A quick fix for you folks having trouble is to add an unused dimension number to a pair of config settings like this:

    S:"Extra dimensions to generate Copper in, separate by ;"=27
    S:"Extra dimensions to generate Zinc in, separate by ;"=27

The source of the problem is in SteamcraftOreGen.java and is related to the fix for #224 

        String[] zincArray = Config.zincDims.split(";");
        final int[] zincIDs = new int[zincArray.length];
        for (int i = 0; i < zincArray.length; i++) {
            zincIDs[i] = Integer.parseInt(zincArray[i]);
        }

        String[] copperArray = Config.copperDims.split(";");
        final int[] copperIDs = new int[copperArray.length];
        for (int i = 0; i < copperArray.length; i++) {
            copperIDs[i] = Integer.parseInt(copperArray[i]);
        }

Try/catch the call to Integer.parseInt() to silently drop bad configuration inputs and the default empty string value.

    try {
        zincIDs[i] = Integer.parseInt(zincArray[i]);
    } catch (NumberFormatException e) {}

**Comment by elifoster** [comment]
@Monstrel I have, but I have also considered redoing all of the worldgen, because the way it's currently done is sort of stupid.

**Comment by elifoster** [comment]
I will look into fixing this either later today or tomorrow.

**Comment by Too-DAMN-Much** [comment]
i changed the configs like another person in the MCF thread said had solved the problem for them and it did appear to fix it, at least short term, and then i realized that the server had crashed while i was alt-tabbed watching a video so apparently it only makes it takes a bit longer to crash, here is the crash report from the server:
http://paste.ubuntu.com/10579788/

**Comment by Monstrel** [comment]
@Too-DAMN-Much I don't think that crash is related; at least I see no evidence in the stack trace.  That one is probably just coincidence.

**Comment by Too-DAMN-Much** [comment]
@Monstrel can you help figure out who it should be reported to then? sorry for the mistake, it happened after updating flaxbeard's is why i thought so.

**Comment by Monstrel** [comment]
@Too-DAMN-Much The error looks like it occurred when minecraft attempted to unload a chunk in the overworld, and the NPE was thrown in CodeChickenLib.  Your crash looks like those reported here: https://github.com/Chicken-Bones/CodeChickenLib/issues/33

In my experience those sort of crashes can be hard to reproduce, so it might not be that big a deal if it doesn't keep happening.

**Comment by elifoster** [comment]
@Too-DAMN-Much That error definitely does not have anything to do with us. Go report it to CodeChickenLib. I'll have a tested fix for the NumberFormatException issue out hopefully in about 5 hours when I get home.

**Comment by ZeekDaGeek** [comment]
This bug is definitely related to Flaxbeard's Steam Power. The way you fix the issue is editing FlaxbeardsSteamPower.cfg

Change "world generation" config values:
```
S:"Extra dimensions to generate Copper in, separate by ;"=1
S:"Extra dimensions to generate Copper in, separate by ;"=1
B:"Generate Copper in the above extra dimensions"=false
B:"Generate Zinc in the above extra dimensions"=false
```

**Comment by ZeekDaGeek** [comment]
What I mean to say is that the problem reported in this ticket is a problem on it's own. I don't think it's related to crash #224. I think this is a separate problem.  If "Extra Dimension" is an empty value then there needs to be a check built in to handle that.

It seems like at the moment Minecraft is freaking out if it tries to check those values and they are empty in certain scenarios, hence the crash stating `java.lang.NumberFormatException: For input string: ""`

**Comment by kylemcqueen75** [comment]
@ZeekDaGeek No one is saying its related to the crash in #224, we are saying its related to the fix for it.

**Comment by elifoster** [comment]
@ZeekDaGeek No. The default value should be blank. Values of 1, 0, and -1 are completely ignored.
