### ISSUE TITLE
Messed up text in book?

### ISSUE THREAD

**Issue by jordsta95** [Flaxbeard/Flaxbeards-Steam-Power#233]
Dunno if this is intended or not, but I am getting this:
http://puu.sh/gw50O.png
I don't know if this is because I set my GUI scale to normal or not, but I don't know what else could cause this, other than intention.

**Comment by kylemcqueen75** [comment]
For anyone to help you they will need the version you are running :)

**Comment by jordsta95** [comment]
1.7.10
0.28.3

**Comment by elifoster** [comment]
That's really strange. I'll look into it when I get time. I've never experienced this issue before. @jordsta95 Did you do anything special to make this happen?

**Comment by jordsta95** [comment]
Not that I know of. It only seems to do it on stuff that spans the two pages, but not always.

However could this just be that I am ctrl+click on the item (in creative mode) to have that pop up? I dunno?

**Comment by xbony2** [comment]
Do you happen to have optifine?

**Comment by jordsta95** [comment]
No, the only thing that may affect GUIs is NEI, but I doubt that would cause this issue, especially as it doesn't display when the book is open

**Comment by Flaxbeard** [comment]
Do you have DragonAPI?

**Comment by Adaptivity** [comment]
If you have DragonAPI, it should be fixed in latest DragonAPI.

**Comment by jordsta95** [comment]
Yeah, I did have DragonAPI, dunno if it's fixed in the latest update, as I haven't touched the pack since the update

**Comment by elifoster** [comment]
Yeah this should be fixed in V5:
DragonAPI: Fixed FontRenderer mod interaction issues (?)
