### ISSUE TITLE
NumberFormatException in server tick loop?

### ISSUE THREAD

**Issue by Kasran** [Flaxbeard/Flaxbeards-Steam-Power#234]
I'm running Minecraft 1.7.10, Forge version 1291, and FSP version 0.28.3. When I try to make a new world, I get this error: http://pastebin.com/2WQkGmnY

It doesn't happen when FSP is removed. My first guess was that it was trying to read a config file from an old version and it wasn't working properly, but then I deleted the config file so it had to make a new one - and it still didn't work. I'm baffled; looking in the source code, everything that could generate a NumberFormatException in that method should be caught.

**Comment by kylemcqueen75** [comment]
Copy of issue #230 :)

**Comment by elifoster** [comment]
Fixed in next version
