### ISSUE TITLE
Crash possibly related to ore gen.

### ISSUE THREAD

**Issue by laserlemons** [Flaxbeard/Flaxbeards-Steam-Power#237]
Loading up my world after updating to 0.28.3 gives me this crash within a couple minutes. It may have to do with loading new chunks.

http://pastebin.com/B5DZbMYP

**Comment by PrototypeAlpha** [comment]
I just got pretty much the same crash (albeit without Fastcraft) when starting a new world with Biomes O Plenty's terrain gen. Same version of FSP.
http://pastebin.com/SSsXVegp
It also happened to the test server I was on just before trying SP...
http://pastebin.com/sf78zfyc

**Comment by Rosethorns** [comment]
confirmed http://pastebin.com/6DD1gxXH

**Comment by elifoster** [comment]
Fixed in next version. Until then, put any integer value in the extra dimensions config options.
