### ISSUE TITLE
ClassCastException crash from Crucible

### ISSUE THREAD

**Issue by zHawky** [Flaxbeard/Flaxbeards-Steam-Power#257]
Hi! seems like Carpenters blocks and your mod partialy incompatible or im something understand :/
http://pastebin.com/CD75vBMD
this happen when im directly stand at hell crucible and just dropin copper dust..

SANTA EDIT FOR A MORE ACCURATE DESCRIPTION:
The Steam Heater tile entity is trying to get cast to the tile entity underneath the crucible, regardless of what the tile entity actually is. This causes a ClassCastException crash.

**Comment by elifoster** [comment]
Oh, I know what's going on. Will fix in a sec.

**Comment by elifoster** [comment]
@zHawky This is fixed in the latest release, 0.28.7.

**Comment by zHawky** [comment]
Well im appreciate your feedback, thanks
