### ISSUE TITLE
Easier Way to Create Brass?

### ISSUE THREAD

**Issue by CrimsonCrystal** [Flaxbeard/Flaxbeards-Steam-Power#258]
Isn't there an easier way to create brass without creating a extremely large system of crucible and molds? Or some way to automate it? Because currently, in order to create brass you have to maunally place in zinc/copper into the crucibles, and then use continuously right click the crucible/molds. It extremely time consuming, even if you use redstone.
My suggestion is too either add a machine that automates brass creation at the expense of steam, or add cross-mod integration into Tinker's Construct, allowing for the mixing of zinc and copper to create brass.
In addition, it seems that other mod's copper, even when having the same ore dictionary, cannot be placed into the crucible.

**Comment by elifoster** [comment]
As of version 0.28.0, you can automate the creation of brass. You can tip the crucible using redstone pulses, and molds can output to pipes/hoppers/whatever. As of 0.28.1, items can be dropped into the Crucible by things other than players. I'm not sure what's up with the OD, but it's been reported.
