### ISSUE TITLE
Cannot add water to flash boiler

### ISSUE THREAD

**Issue by AcidDotCom** [Flaxbeard/Flaxbeards-Steam-Power#261]
Hi guys, 
It seems I cannot add water to the flash boiler. When I'm using a bucket on it it just disappears...
I've tried rebuilding it and nothing helps. I've also updated to the newest version on the mod and it's still the same. Anybody have an idea what's wrong with it?

**Comment by justicesays** [comment]
I've had issues where the steam , water and fuel status of flash boilers is very unreliable when checked from the GUI. This is on a server, so I'm not sure if the same issues persist in single player.
Have you tried putting the full bucket in the bottom slot of the boiler GUI and seeing if it empties?
Did you put fuel in as well to see if steam would start? Try attaching a gauge to see if steam is being generated. Have you tried setting up an Archimedes screw to fill it once it's been bootstrapped?

**Comment by AcidDotCom** [comment]
I've done all of the above...nothing helps and nothing is being generated. 
I think it has to be something with my game cus I'm using a blast off modpack and after the update it stopped. I've downgraded to the previous version, but it did not fixed it.

**Comment by AcidDotCom** [comment]
Hello again. As I said before it was an issue in the modpack probably. Finally there is an official update in the FTB launcher for Blast Off (1.3.3) and after the downloading it I had to re-build the flash boiler and quit the game and quit the launcher too. After that restart it is working fine.
Just FYI...all this 1.3.3 update does is bringing the newest (31st of Match) version of Flaxbeards and Pneumaticraft, but updating it manually did not fixed the above problem for some reason.
Anyway thanks for help and I'm off to generate some steam :)

**Comment by elifoster** [comment]
I have absolutely no idea why that happened or why it was fixed. The Flash Boiler has not been touched in about a month. I'm blaming another mod or poor configuration done by karmarcharger.
